create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid references auth.users(id) on delete set null,
  referral_code text not null,
  bonus_amount numeric(10, 2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'qualified', 'paid', 'cancelled')),
  created_at timestamptz not null default now(),
  qualified_at timestamptz,
  paid_at timestamptz
);

alter table public.delivery_profiles
  add column if not exists referral_code text;

create unique index if not exists delivery_profiles_referral_code_idx
  on public.delivery_profiles (referral_code)
  where referral_code is not null;

create or replace function public.generate_delivery_referral_code()
returns text
language plpgsql
as $$
declare
  candidate text;
begin
  loop
    candidate := 'SC' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8));
    exit when not exists (
      select 1 from public.delivery_profiles where referral_code = candidate
    );
  end loop;
  return candidate;
end;
$$;

create or replace function public.set_delivery_referral_code()
returns trigger
language plpgsql
as $$
begin
  if new.referral_code is null or btrim(new.referral_code) = '' then
    new.referral_code := public.generate_delivery_referral_code();
  else
    new.referral_code := upper(btrim(new.referral_code));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_delivery_referral_code on public.delivery_profiles;
create trigger trg_set_delivery_referral_code
before insert or update on public.delivery_profiles
for each row execute function public.set_delivery_referral_code();

update public.delivery_profiles
set referral_code = public.generate_delivery_referral_code()
where referral_code is null or btrim(referral_code) = '';

create index if not exists referrals_referrer_idx
  on public.referrals (referrer_id, created_at desc);

create unique index if not exists referrals_referred_user_unique_idx
  on public.referrals (referred_user_id)
  where referred_user_id is not null;

alter table public.referrals enable row level security;

drop policy if exists "Users can view their own referrals" on public.referrals;
create policy "Users can view their own referrals"
  on public.referrals for select
  using (auth.uid() = referrer_id or auth.uid() = referred_user_id);

drop policy if exists "Users can create referrals for themselves" on public.referrals;
create policy "Users can create referrals for themselves"
  on public.referrals for insert
  with check (auth.uid() = referrer_id);

drop policy if exists "Referred users can create their referral record" on public.referrals;
create policy "Referred users can create their referral record"
  on public.referrals for insert
  with check (auth.uid() = referred_user_id);
