create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 3 and 160),
  description text not null check (char_length(btrim(description)) between 10 and 5000),
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  admin_reply text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_tickets_user_created_idx
  on public.support_tickets (user_id, created_at desc);

alter table public.support_tickets enable row level security;

drop policy if exists "Partners can view their own support tickets" on public.support_tickets;
create policy "Partners can view their own support tickets"
  on public.support_tickets for select
  using (auth.uid() = user_id);

drop policy if exists "Partners can create their own support tickets" on public.support_tickets;
create policy "Partners can create their own support tickets"
  on public.support_tickets for insert
  with check (auth.uid() = user_id);
