-- Optional activity tables used by the delivery partner profile cards.
-- Run this once in the Supabase SQL editor.

create table if not exists public.delivery_gigs (
  id bigint generated by default as identity primary key,
  delivery_partner_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  amount numeric(10, 2) default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.delivery_offers (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  amount numeric(10, 2),
  is_active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists delivery_gigs_partner_idx
  on public.delivery_gigs (delivery_partner_id, created_at desc);

create index if not exists delivery_offers_active_idx
  on public.delivery_offers (is_active, created_at desc);

alter table public.delivery_gigs enable row level security;
alter table public.delivery_offers enable row level security;

drop policy if exists "Partners can view their own gigs" on public.delivery_gigs;
create policy "Partners can view their own gigs"
  on public.delivery_gigs for select
  using (auth.uid() = delivery_partner_id);

drop policy if exists "Authenticated users can view active delivery offers" on public.delivery_offers;
create policy "Authenticated users can view active delivery offers"
  on public.delivery_offers for select
  using (auth.role() = 'authenticated' and is_active = true);
